name: "[CD] Continuous Delivery"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependendcies"
        run: "npm ci"
      - name: "Deploy"
        run: "npx vercel --prod --token=muH4JZz1x9jMoKPsiAnGWbRD"
