name: "[CD] Continuous Delivery"

on:
  pull_request:
    types: [opened, synchronize]

env:
  VERCEL_TOKEN: muH4JZz1x9jMoKPsiAnGWbRD
  VERCEL_ORG_ID: team_mto8fzSd5i3z9qcyH6wLxo7b
  VERCEL_PROJECT: prj_pUT2gtygKYLe9S28QyyPGPlkX7It

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install dependendcies"
        run: "npm ci"
      - name: "Deploy"
        run: "npx vercel --prod"
